# Generated by Django 4.2 on 2023-04-08 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('presupuesto', models.DecimalField(decimal_places=3, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nif', models.CharField(help_text='Ingrese el nif', max_length=9)),
                ('nombre', models.CharField(help_text='Ingrese el nombre del empleado', max_length=100)),
                ('apellido1', models.CharField(help_text='Ingrese el primer apellido', max_length=100)),
                ('apellido2', models.CharField(blank=True, help_text='Ingrese el segundo apellido', max_length=100, null=True)),
                ('codigo_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_empleado.departamento')),
            ],
        ),
    ]
